[project]
name = "imdavidb"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
dependencies = [
    "pymysql>=1.1.2",
    "sqlalchemy>=2.0.45",
    "streamlit>=1.24.0"
]
